apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2504
  namespace: app-2504
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2504
  template:
    metadata:
      labels:
        app: app-2504
    spec:
      containers:
      - name: app-2504
        image: tuantrana2000/2504-tuantran-repo:tag-34
        ports:
        - containerPort: 8080
      # Registry docker that create on k8 Cluster
      imagePullSecrets:
      - name: 2504-tuantran-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-2504-svc
spec:
  ports:
  - port: 30001
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app-2504-svc
  type: ClusterIP
